export default {
  email: '',
  password: '',
  firstName: '',
  phone: '',
  location: '',
  addressLine1: '',
  addressLine2: '',
  city: '',
  state: '',
  zip: '',
  licenseNumber: '',
  licenseState: '',
  birthday: '',
  expiration: '',
};
