export default {
  email: '',
  password: '',
  firstName: '',
  lastName: '',
  phone: '',
  placeName: '',
  latitude: '',
  longitude: '',
  street1: '',
  street2: '',
  city: '',
  state: '',
  zip: '',
  number: '',
  licenseState: '',
  birthDate: '',
  expiration: '',
  experience: '',
  offerPerWeek: '',
  rideshare: '',
  wantsElectric: '',
  accountType: 'waivework',
};
